apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@gitlab.com:bruninho51/projeto-controle-gastos.git'
    targetRevision: main
    path: monitoring
    helm:
      releaseName: prometheus
      valueFiles:
        - values.yaml
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
