apiVersion: v2
name: prometheus-stack
description: Instala o Prometheus com customizações
type: application
version: 0.1.0

dependencies:
  - name: prometheus
    version: 25.21.0
    repository: https://prometheus-community.github.io/helm-charts
