kube-prometheus-stack:
  grafana:
    enabled: true
    admin:
      existingSecret: grafana-user
      userKey: grafana-user
      passwordKey: grafana-password
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - grafana.orcamentos.app
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.orcamentos.app
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL  # Procurar em todos os namespaces
        label: grafana_dashboard
        labelValue: "1"
        folder: /tmp/dashboards
        folderAnnotation: grafana_folder
      datasources:
        enabled: true
        searchNamespace: ALL  # Procurar em todos os namespaces

  # Configurações importantes para dashboards padrões
  grafana-dashboards:
    enabled: true  # Habilitar dashboards padrões

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: monitoring-prometheus-auth@kubernetescrd,monitoring-prometheus-ratelimit@kubernetescrd
      hosts:
        - prometheus.orcamentos.app
      tls:
        - secretName: prometheus-tls
          hosts:
            - prometheus.orcamentos.app

  alertmanager:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: monitoring-prometheus-auth@kubernetescrd,monitoring-prometheus-ratelimit@kubernetescrd
      hosts:
        - alertmanager.orcamentos.app
      tls:
        - secretName: alertmanager-tls
          hosts:
            - alertmanager.orcamentos.app

  # Garantir que os dashboards padrões sejam criados
  defaultRules:
    create: true
  
  # Esta é a seção correta para habilitar dashboards
  grafana:
    defaultDashboardsEnabled: true  # Adicionar esta linha
    
  kubeStateMetrics:
    enabled: true
    
  nodeExporter:
    enabled: true