kube-prometheus-stack:
  kubeEtcd:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false
  
  defaultRules:
    create: true
    rules:
      etcd: false
      kubeControllerManager: false
      kubeScheduler: false
      kubeProxy: false

  loki:
    enabled: true
    persistence:
      enabled: true
      storageClassName: local-path
      accessModes:
        - ReadWriteOnce
      size: 10Gi

  promtail:
    enabled: true
    serviceAccount:
      create: true
    config:
      clients:
        - url: http://loki:3100/loki/api/v1/push
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app]
              target_label: app
            - action: replace
              source_labels: [__meta_kubernetes_pod_namespace]
              target_label: namespace
  
  grafana:
    enabled: true
    persistence:
      enabled: true
      storageClassName: local-path
      accessModes: 
        - ReadWriteOnce
      size: 1Gi
    grafana.ini:
      server:
        http_addr: 0.0.0.0
    admin:
      existingSecret: grafana-user
      userKey: grafana-user
      passwordKey: grafana-password
    defaultDashboardsEnabled: true
    
    sidecar:
      dashboards:
        enabled: false
      datasources:
        enabled: true
        searchNamespace: monitoring
        env:
          - name: METHOD
            value: LIST
    
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - grafana.orcamentos.app
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.orcamentos.app
  
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      retention: 30d
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
    
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: monitoring-prometheus-auth@kubernetescrd,monitoring-prometheus-ratelimit@kubernetescrd
      hosts:
        - prometheus.orcamentos.app
      tls:
        - secretName: prometheus-tls
          hosts:
            - prometheus.orcamentos.app
  
  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
    
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: monitoring-prometheus-auth@kubernetescrd,monitoring-prometheus-ratelimit@kubernetescrd
      hosts:
        - alertmanager.orcamentos.app
      tls:
        - secretName: alertmanager-tls
          hosts:
            - alertmanager.orcamentos.app
  
  kubeStateMetrics:
    enabled: true
  
  nodeExporter:
    enabled: true
    hostNetwork: true
    hostPID: true
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
    serviceMonitor:
      enabled: true
      jobLabel: jobLabel
  
  kubelet:
    enabled: true
    serviceMonitor:
      cAdvisorMetricRelabelings:
        - sourceLabels: [__name__]
          regex: '(container_cpu_usage_seconds_total|container_memory_working_set_bytes)'
          action: keep