apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orcamentos-api
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: orcamentos-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
