apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orcamentos-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@gitlab.com:bruninho51/projeto-controle-gastos.git'
    targetRevision: HEAD
    path: 'k8s/app'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: orcamentos-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
