---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-registry-secret
  namespace: orcamentos-app
spec:
  encryptedData:
    .dockerconfigjson: AgBspIHZ4KN8iEwZWnP25FX0CPTNH8YvLXGMNnOXmypMkE6nxDkZbdLbKE3VHQLAMFpbHyvHLEfZ7fsKqhMpdK+5fqylSiDhejY2wl/V59auEy4G3f+nitMeYnOjJu2r87Sl6RY5NZyEC08Ov9fEo9CsJZmxKyTj+lCAxGGLJlPBgR2Xg9DJpSBa/McseakemMuSGC55RqKAH+vZoF/ZeyPk6RpmZ80bOkbp/SmYU0IZ9DlpX0NybcQqxDOQ5eFWbs1yDWf2SWajf27xw/cQvR7BThEBGZ/yOF7ZayMcMV2ROcoWp4RpHJGzgMS1qTZ+sH+JGQ03T34U/RspEkJV7kw+D1VeICjKf8PZ2fsn2yuXNrk8BNeAwZ8A4XqJtNjQOBTVVGRcdcMVg+BX5V5Ty2a4LR+R29M/80vGwYCJ86y0my2gcmS2RBVsjfhXcLg/QcfkMzjtc/+ad5lnzKgr02tlXccipQgrSC52FzSE7xjppaU6XgQhdvAU0qjwrbzsR6ZRPKYs0ISrJZzlbIJqdG+aZTPs6GRWHM0V1Jv/Ac+WRLhbyfjl1Ubz4M78F2pTXGFoVsiCDTTDaa8PIuftZyBSAZnXoS+F1GiW7OVkoGY9/as7ArPkT8uM7cPoSj3rLIgEvurIiI/AzyDog3+1iPtaIX3A2tAH0Rp5/VmyTwsMLYAwmYOya2VFtnedZJTupocF950Ymg25cjN1X9QCt8ctYhxyKB/XeCO82NE2RheLQFttR3+Dcg5d4xKejZvk1eZkz15gLWijVTzSL58cjYo9TjfcaV+/hmDpK5OOVuE1mA3wgDK2x+JVVtNSZvyaq96hV1TT5wKafLYpnlAufGce+iP4a0Z5b6X4ls64sPaC2ICeQgsEGyXiavdfIk7N1iBD1ofsmcj+UTGoBO3CHplnedRdpC5W14wUZC+IPoeMWchu9TXAs/HEbi4fLGqHDhHsEJA5u3SeC3wFeaDkxaSJE+ZxtJuv4v12yNN8yTAAwTagJjEFih/3YWaVFEb1wprFjeLMxDQEbRlOxOfB+18A2IuowPRpwEbiUeDPBQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-registry-secret
      namespace: orcamentos-app
    type: kubernetes.io/dockerconfigjson
