apiVersion: v1
kind: Service
metadata:
  name: nest-app-service
  namespace: orcamentos-app
spec:
  type: NodePort
  selector:
    app: nest-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
