apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate-job
  namespace: orcamentos-app
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: prisma-migrate
          image: orcamentos-app:latest
          imagePullPolicy: Never
          command: ["sh", "-c", "npx prisma migrate deploy"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: orcamentos-api-secrets
                  key: DATABASE_URL
