apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-auth
  namespace: monitoring
spec:
  encryptedData:
    grafana-password: AgBI25lBluxiA/4P9AInXiBbch9WYPLulAfpQdsAszwTq7p8yicgsAgp6j2cRTILG1m3OGkg7msqUN+XZ8ws118H9pflephGi+vweeK0rLcFVknqWzameXb+jrhX30j8Hx9KiS4WqT1Ug97v/JUtHKSG63bwZwysMq+W8VW0FKwuwLtvZafwD>
    prometheus-password: AgBJVYErCA+BNmzcy7ayKmzIKGpbB2i3nGR693+XlwxbvXUX1+DU2Jr9ic+XoD1Rp3hmdzKco+vfiucAjRNNP42v4jMJ7/SAEVLw1uOuREuezBGuLhwBBIDfS6xa5mLzpLKS6mCfahX52oXRDMAeZ79QdE5/l0lKOgjcbN/nqexVBfq3zX>
    users: AgBQELuTq4XEJ5elDiR6Ey+UgG3+EHl9IYh4S/xy5U8EMkFNjXh5KqtqORqZAzmCOf/FFKgwFd/c7YaL+1p0zsPdB9p9tatgojqH9lJWsfWeGPBmH5OZnMhuNw9lQ5cqmZMZQ67/7ZRqIsknFeyIkfIXSDZobFaVuZ5tDVV5SGhLQlf6qn7qCzJA3LLtaRGu>
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-auth
      namespace: monitoring
    type: Opaque