apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-auth
  namespace: monitoring
spec:
  encryptedData:
    grafana-password: AgBpUgxuwXlbL1dqPCrdAwvdvvpczDOhVmdnj3uYVuOhYP83A+W0yLuL9osOeX/jMNBSy30yWp9O2csxr1UQ/H3t9t41keGp74lYsIkzNbYZWtWkLyL9KzzI+bT0cmM5zYv8+3mXpQDsuQtPnLTaUf7SWGU+KZGzxZT+EcT0DsHN6YOLG1Tkw>
    prometheus-password: AgC9EA2feOlBRCI4LUXlfqdGqXbrRDX7AIepqhn/ZW2iEVoASStR2OV2pmbUGjZMiWC7745B4MuVfULAR5Jj1k2N1bmPbUZDWhobpzRNc6Fm32JUOSalOI1uhKuCv1Gp7ZpmpACda4mEWC3hBlnNAQgc5yN1jJ8UVkSWwuLq+VUj9pprEl>
    users: AgCQq3fmi0dAC/y5dCIJOUAfPGbWPAsCm55KJScVJQ873LU5c/5RryNHFIyLzpK4SZaxRHMwyt5RNUKAfJChp8id3cJdpp5VSyhs7bmOVvxFueh2zqxbaGjp3N52HEfOXAnT9GI+OxH7i7/01aYsByGRYamPUokkbJXHFWjrlEnuyWa5HSue9pHLLyXpD5u2>
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-auth
      namespace: monitoring
    type: Opaque