apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-auth
  namespace: monitoring
spec:
  encryptedData:
    grafana-password: AgAOhLg3PJujL7ewUo7u9U2iBGWwckLM3MZMw/OiBAf++83Bdjafnh8JpNn7VNuX7IgptXbRPv7F1ZcXnr0ZyWFKLwT+pSi1KKpW8eJ+x8KPuY/dNJ7kC6gbimNkN7iJvUo8djhQgqOc5AU6kDwXpyUaZxJGo9Yua7a1FJ8KdMq7cmMKeKqC1>
    prometheus-password: AgDQeOKTbjohnHr4t5P4KtGck3a5CxOVnw75vujz3jXWixBnD98iD/mht542aQ8tuz7dGW2HKKilgjn8ogYAFcp6JQacoMUKxt8j5uIbmHtCbQBtlIAtEYRWrLXN4ey+VFEfQCrnTJm1aEdeITUQH3iq0JKNIZtihMb/mUbTA+wJhS1fuA>
    users: AgB+KYdCKSzKXyLQZG/rhAK7aRDtPv5DsuARU5sV/52alZ+6R0r47cgiBfwWnn/qT/sgFVhNFJpn/0PhDzHma+F8owmANSDpigxlzUFrY8o9I3lVVmd3HluMJD+bHn6EFeoYXa6Wod6Hb8IOzCiU6R9y6l9K2bjJRKD+2cuwornkWKGxDacZujb+8N2Ag4T7>
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-auth
      namespace: monitoring
    type: Opaque