apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-auth
  namespace: monitoring
spec:
  encryptedData:
    grafana-password: AgA33+nhR+eWICLJL/WC1ylr9iemhbobKWPIMd4mf0Ykxavk0bP0Lol+++dz88tHzAR0GeMAE5UwO8B0FNCe2XdZ9Ta5ScbLElES44DFbLcmlQJYqpC2xKFpYdG5Q9jM6yoDI5jQyOShbfnjghgGcDCb2F965mBykF8cB39ooFkjxWPAv6VVb>
    prometheus-password: AgBCU5rsPTOU6Hk7h/xlZt8nzlKT+2DxW2HQbW/1SuXRgDc7mk/JgwZRb2FnpN3gFqpcPVfEQtsGnjDjgwTkFcLXRZ8XH0mXqkq7Mg+KqQu+IwFudTYvvRPJMKSaXXBbbCm+TQmBrM6H+KCE6odJrpeRUb3gOsVtKUalq1GwNwdsN+UjJX>
    users: AgASPqYOZE55Q2K15hEl+eObXY42ztHx5nezUbowp3G4AkJvQZvQs24FM62kPiMjFqTAik1M88vGcgYaUo7830Ea4p/DKxpsaMwbCMd6Jnz7LCwZl/SEcR2E+/3GWVnbq0DVPEZzX6xmsckV8O4Ywynoo7PTZm0AxOB6pEvsIbEETQTJSlECQ2Ee+8msgJ1Q>
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-auth
      namespace: monitoring
    type: Opaque