apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-auth
  namespace: monitoring
spec:
  encryptedData:
    grafana-password: AgCvH++D/9NDGhWA8neaX9u/Sqf/0BD5aw2wwG4IxveqX2Ozf9vhZ4Y1dDSTg1t+g7NMN2QYAiIBYxwKbuS2idAtmbbJgGSTzXlB951dPD7j4l2EChkKDKhR/yH1p9g9t8x/IcjB8hgq9Ultgvxrz3kCOWi49n0JfC99DjNnIoDviMZNRnsea>
    prometheus-password: AgDDcGTI3/Kha/Ml0so+1fVQpsW1bpCPeSr9ZYUjk6Np/JlpupkqVRRqRjRgDAWhlYG5hox1dUKXJjnd9usEliczJ8gqqax4q3Kl9qmMZsQ7XmRs8uuz7B/xBoaAgXqstwXbgkHykz9OBDnvvsfkE3Age9C5m+yx6f56bgTWqmfvvlW0xu>
    users: AgAr/L8q0sLrMeReXRERPOGtJmodQNeIa9F/h9qoAWTG4vwGdDtz+VbsfIX9SNq054evr/8pCS5J05dwJuAd5l8OBkkqVhR0Bmj6nQHHwLtKjT53G2RBxJp6oHCpQMtlZOeONqiSVgcgLhY2NoPtPUlMLHmfvj5x9YdQwMLr62c+RV8XEzfwdUebHc6bMFiV>
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-auth
      namespace: monitoring
    type: Opaque