apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-auth
  namespace: monitoring
spec:
  encryptedData:
    grafana-password: AgC/npARzFBNMRtApraGjQA6LNH3d3MNvKAnDHiCSxFzVENJCKRE8FDmJ5xOmnrOxQY9bZMVUB9VTjQk+ecTFXV/URDq1riZpMNwqRBjafKF6nX9vEIcgq6SQOWzmyHcBf6BWeFT/dULfWzoG8l8xsfeSWkWCCWUxfCKwAh/aNuXvkNOlRHTo>
    prometheus-password: AgApKw17vOOdKExej7NPsSnsgG2sZ3r8qnteTIKxDuYM9SQmoY1cSgST3BmOG4f96c7uY0vrj8YWbpvfIqIga//SuTJexW3Bw+YmIrEHkgusr+K4T2U10yiWJxPoOEYK51EXTePAl6DwkZZaIDJQSbf9ss/WRo5Ct8C6Cq+gntgmMAWQ8q>
    users: AgDhcwYnHPwY53AmCB3plc1D7kOUrd5uCzaADGxJewfgFOQ/MhuAtPuygrH4NKhrEeyGQcJ8RuTXIfDZXqYvTZ7CxT/gdGdHVjDMAmzSLEPBxFgKs4NEXeYRFB1LPTsNg6Z7nmCJ40BTlk6wLpb/K142oAPHozGiOYabs98QnKKHwN/WMtBVXuLnmWJx/Pab>
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-auth
      namespace: monitoring
    type: Opaque