---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-user
  namespace: monitoring
spec:
  encryptedData:
    grafana-password: AgDlHLHT6v8KqAwxb/bSfXMxkHBzds8HgHpXjVx32CBMpo53KtEwo4LBcDtzkTeWNvUCHnP7yuZS0ypp9OU2SAp5eSQSJzAoqiWi1vEtjwNQz8q4UxrsSzPHa9UojSjWa0bEkBApSf+6KFsVkcm3R68E2fpl889M2ZOUYNKWSB30GyMI73A6+cnvxu6tvOepynvOfGaZZ5GQNrJbkC/Fi+EWbCOr0ntRP/TV4BDb1t/45j+LYM2AJi0ZwRx2rPa5d0Ane68Pd3hJkFgMzIRPUGbo9iSavXKValuPy1/itg5lFeiKGWwLmzBfrZB+LkNjN2HxY6ITOvgJhmR3GaH7F9seyaZLSBWP+oimIrVtMb2mOTtXOTwi9fe4JLWZdD2FSeQ2xlOCVGx4c29rklfH49tnoCF1dKvGgQ2ecaaK23QwcKnjNVM5lpRp2XR/0HBGh7KFbZV/ctfkOW42jkcAYaqDYQHmgoTCZNHsCuHtwqGL/3xC2T9QP3thk7BV3llktoW9IDrSsJ8Gaff9ODAGwFsBwcphRAHr6ovX52JuC1pgL81oC5ESdyymf5Mt3cnR1TWUDbF22hfx99iwgvlx5TgppbgTJqJRRyuWWH5V0+CQXPQkJdRfCXeBbR5BFvpaJpkzRq5fSDZkq+Oea7iumjlk1J3gSQajfkZeHd7wr8G8Gi2wa5ffCuflTzh/Tx/nL/miIjdM7F076GmdHucn8JFT
    grafana-user: AgBm8K/BxrzV86uvna8mL0/3HUbJ1ziiKiUJ2IcckuwbD8HkW4n4fQT3pq4KsmvpXUynpMyFDisYzZwzqhx9ZJv8RAonhYUxxw/Xhlq8Vlfo9uhqLZb8A/nUNFIIpgeEEd9PsUilNpU1WL9S1UAiI40E1o3asiZPP2JD4swowH9pRuTRYrGmugPYeUq0UoODVI90yP4W9512iiP/jILmhwEK6xPdnY9xxnir6mdXyNBJb2Pt9q0+YGbmIYbAwB/x4RTpFgtCJ5rtSgygMsZYXOB6D7pROWA7j/Xb7EMNQLdc38XAsrfVYJq+uNpuFE8rhTm/445xrovk1kMylRil9SKy4tsf2GQvIKPL9/osaO9W06mVDcC4l4jO1xDCPwCkU3omuJRVzTC5VpOOCE2UarnLuU15wWaexFZLXZwDMPJi+avls2eNXGEbyt2cAZ1cahnfyUdQkVUxZxKknMI3c7Z1Gdgfy6NCmqjXhOQv2TBH286/DeDaY4KjmIVquKNSjmFprOqPu8qTcKSzmRKB1GD5Ef4Qg34D8EHrgriRDyVzVXVYHpTP+y4VTB0mZPEXc6kYbeBjcFWvLxvLlSJi7A/1iZdIHZhp+MZuF3utFBfab7ZgvGTG2/1wEqczSruSPikT0ApZky6xt1qGUtkA1FCulCsu6Ny3Gy7Nh1TccaxxMZqnnLvNYrNLXaYkuS0MNFPGjk9f5EN754mUY8hcZ+v7jgq5V4EJzAM=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-user
      namespace: monitoring
    type: Opaque
