apiVersion: v2
name: vault-app
description: Chart personalizado para instalar Vault
type: application
version: 0.1.0
appVersion: "1.13.0"
dependencies:
  - name: vault
    version: 0.26.0
    repository: https://helm.releases.hashicorp.com