import { Test, TestingModule } from "@nestjs/testing";
import { BadGatewayException } from "@nestjs/common";
import { GeminiService } from "./gemini.service";

function mockFetchResponse(regex: string | null, ok = true, status = 200) {
  const text = regex === null ? "" : JSON.stringify({ regex });

  return {
    ok,
    status,
    json: jest.fn().mockResolvedValue({
      candidates: [{ content: { parts: [{ text }] } }],
    }),
    text: jest.fn().mockResolvedValue("erro"),
  };
}

describe("GeminiService", () => {
  let service: GeminiService;

  const originalEnv = process.env;
  const fetchMock = jest.fn();

  beforeEach(async () => {
    process.env = {
      ...originalEnv,
      GEMINI_API_KEY: "fake-key",
      GEMINI_MODEL: "gemini-2.0-flash",
    };

    global.fetch = fetchMock as unknown as typeof fetch;
    fetchMock.mockReset();

    const module: TestingModule = await Test.createTestingModule({
      providers: [GeminiService],
    }).compile();

    service = module.get<GeminiService>(GeminiService);
  });

  afterAll(() => {
    process.env = originalEnv;
  });

  describe("gerarRegexNotificacao", () => {
    it("should return the regex generated by Gemini when it is valid", async () => {
      const regexValida =
        "Valor: R\\$(?<valor>[\\d,.]+).*Estabelecimento: (?<estabelecimento>.+)";

      fetchMock.mockResolvedValue(mockFetchResponse(regexValida));

      const regex = await service.gerarRegexNotificacao("titulo", "corpo");

      expect(regex).toBe(regexValida);
      expect(fetchMock).toHaveBeenCalledWith(
        expect.stringContaining(
          "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent",
        ),
        expect.objectContaining({ method: "POST" }),
      );
    });

    it("should throw BadGatewayException when the Gemini call fails", async () => {
      fetchMock.mockRejectedValue(new Error("network error"));

      await expect(
        service.gerarRegexNotificacao("titulo", "corpo"),
      ).rejects.toThrow(BadGatewayException);
    });

    it("should throw BadGatewayException when Gemini responds with a non-ok status", async () => {
      fetchMock.mockResolvedValue(mockFetchResponse(null, false, 500));

      await expect(
        service.gerarRegexNotificacao("titulo", "corpo"),
      ).rejects.toThrow(BadGatewayException);
    });

    it("should throw BadGatewayException when the response has no text", async () => {
      fetchMock.mockResolvedValue(mockFetchResponse(null));

      await expect(
        service.gerarRegexNotificacao("titulo", "corpo"),
      ).rejects.toThrow(BadGatewayException);
    });

    it("should throw BadGatewayException when the response is not valid JSON", async () => {
      fetchMock.mockResolvedValue({
        ok: true,
        status: 200,
        json: jest.fn().mockResolvedValue({
          candidates: [{ content: { parts: [{ text: "not-json" }] } }],
        }),
        text: jest.fn(),
      });

      await expect(
        service.gerarRegexNotificacao("titulo", "corpo"),
      ).rejects.toThrow(BadGatewayException);
    });

    it("should throw BadGatewayException when the regex is missing the required named groups", async () => {
      fetchMock.mockResolvedValue(
        mockFetchResponse("Valor: R\\$(?<valor>[\\d,.]+)"),
      );

      await expect(
        service.gerarRegexNotificacao("titulo", "corpo"),
      ).rejects.toThrow(BadGatewayException);
    });

    it("should throw BadGatewayException when the regex is syntactically invalid", async () => {
      fetchMock.mockResolvedValue(
        mockFetchResponse("(?<valor>[\\d+(?<estabelecimento>.+)"),
      );

      await expect(
        service.gerarRegexNotificacao("titulo", "corpo"),
      ).rejects.toThrow(BadGatewayException);
    });
  });
});
